---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribbble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Sam Collins
  homepage: http://zocial.smcllns.com/
  twitter: https://twitter.com/smcllns
  dribbble: http://dribbble.com/danielbruce
  github: https://github.com/samcollins/css-social-buttons/
  license: MIT
  license_url: http://opensource.org/licenses/mit-license.php

  css_prefix_text: "icon-"
  columns: 4

font:
  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: zocial

  fullname: Zocial
  familyname: Zocial

  copyright: Copyright (C) 2012 by Sam Collins

  ascent: 850
  descent: -150
  weight: Medium

glyphs:
  -
    css: duckduckgo
    code: 0x21
    uid: 446acc3b40ca5654627ffb8bc6b906e7
    search: [duckduckgo]
  -
    css: aim
    code: 0x22
    uid: 86009860c8331a1d90ae269432d6e24f
    search: [aol, messenger]
  -
    css: delicious
    code: 0x23
    uid: 1e2035b7cbaeb3d902cf9849e456069d
    search: [delicious]
  -
    css: paypal
    code: 0x24
    uid: f5281239de27061e68f4367ba3efee15
    search: [paypal]
  -
    css: flattr
    code: 0x25
    uid: c71d7db10ede1349b3a8ae0293b1dbf8
    search: [flattr]
  -
    css: android
    code: 0x26
    uid: aaf371ab44841e9aaffebd179d324ce4
    search: [android]
  -
    css: eventful
    code: 0x27
    uid: ca8881bd09267577150cc4637dc65572
    search: [eventful]
  #-
  #  css: 28
  #  code: 0x28
  #  uid: 314d153e4db164ff47849f9ff5a2ffd9
  #  search: []
  #-
  #  css: 29
  #  code: 0x29
  #  uid: 4b18775e2b9d532b915423af84bcbd2b
  #  search: []
  -
    css: smashmag
    code: 0x2a
    uid: 5556b88a0dc630940f326ab2ffbe7ccc
    search: [smashmag, smashing]
  -
    css: gplus
    code: 0x2b
    uid: e566d3f1d24f22981f6552d5188e7265
    search: [google, plus]
  -
    css: wikipedia
    code: 0x2c
    uid: 64c2f859fa518d38db7ec7532855ae34
    search: [wikipedia]
  -
    css: lanyrd
    code: 0x2d
    uid: 846fae80e47217662041242ee1f15a83
    search: [lanyrd]
  -
    css: calendar
    code: 0x2e
    uid: fe4b70ed76eb9a48877632032b33c942
    search: [calendar]
  -
    css: stumbleupon
    code: 0x2f
    uid: 76a8a77019900916d16bad3eb4ee432c
    search: [stumbleupon]
  -
    css: fivehundredpx
    code: 0x30
    uid: d089814548af1441aa00ecec47851f38
    search: [fivehundredpx]
  -
    css: pinterest
    code: 0x31
    uid: 799d6108751f684ac9d018983251a08f
    search: [pinterest]
  -
    css: bitcoin
    code: 0x32
    uid: 523e56b66e166a5bb7b823844bdf56e6
    search: [bitcoin]
  -
    css: w3c
    code: 0x33
    uid: 288a62ca532f76053c4a834ba3746ea2
    search: [w3c]
  -
    css: foursquare
    code: 0x34
    uid: ffecc77dcd9b9dff653ff88b508220d4
    search: [foursquare]
  -
    css: html5
    code: 0x35
    uid: d4d52a448819e8d5e849b8126416b640
    search: [html5]
  -
    css: ie
    code: 0x36
    uid: 63208f7386b9384ba1291832de6ceee7
    search: [ie, explorer]
  -
    css: call
    code: 0x37
    uid: eb2d71e114d99d85b2ae28ab70d981a6
    search: [call]
  -
    css: grooveshark
    code: 0x38
    uid: c9829449672245d22b3d43d7d1a7cc90
    search: [grooveshark]
  -
    css: ninetyninedesigns
    code: 0x39
    uid: 0aeb6f0ea0d091185f5c775401708aa1
    search: [ninetyninedesigns]
  -
    css: forrst
    code: 0x3a
    uid: 2f6ed771cf99f6826343c31ed0b08026
    search: [forrst]
  -
    css: digg
    code: 0x3b
    uid: 8625d6e45fba1219638069e21eedbce8
    search: [digg]
  #-
  #  css: 3c
  #  code: 0x3c
  #  uid: 8df6789d05b0e0686d20de0d93ce3ed7
  #  search: []
  -
    css: spotify
    code: 0x3d
    uid: e4b799ca3860a8276dba05b11d7e13db
    search: [spotify]
  -
    css: reddit
    code: 0x3e
    uid: b3a537446285bb3510bba57d20374818
    search: [reddit]
  -
    css: guest
    code: 0x3f
    uid: e2a0b3edf53a477f66d077cb907e2ab5
    search: [guest]
  -
    css: gowalla
    code: 0x40
    uid: 56a3e7f58bbb15252d06a4735e8299dc
    search: [gowalla]
  -
    css: appstore
    code: 0x41
    uid: 1dbc2b4a7f00ef209a85e4b5d9fedec4
    search: [appstore]
  -
    css: blogger
    code: 0x42
    uid: 2dd7e3046b63beb19616dce63c5782a6
    search: [blogger]
  -
    css: cc
    code: 0x43
    uid: 959c9a2360ed00ec9c0a75562d30edc4
    search: [creative commons]
  -
    css: dribbble
    code: 0x44
    uid: 003ba8187d6b00ec3e1ba75d00f1246a
    search: [dribbble]
  -
    css: evernote
    code: 0x45
    uid: 366510ecfb08cd0110134b1ea907fb81
    search: [evernote]
  -
    css: flickr
    code: 0x46
    uid: 231eeeedfdda9dd5d03dc8d03060007d
    search: [flickr]
  -
    css: google
    code: 0x47
    uid: 6d6d0efe9717ec2962ef0a77c6210df9
    search: [google]
  -
    css: viadeo
    code: 0x48
    uid: cf31b05e6409526bbea832ca960777ed
    search: [viadeo]
  -
    css: instapaper
    code: 0x49
    uid: 5cf33e5f0b89834df4fb10609aec90d6
    search: [instapaper]
  -
    css: weibo
    code: 0x4a
    uid: 3a171c02a5096c63c7c0e2e84d5eeb5a
    search: [weibo]
  -
    css: klout
    code: 0x4b
    uid: f35cf173c6dd32fa6a83208aeb26b527
    search: [klout]
  -
    css: linkedin
    code: 0x4c
    uid: cc4e62d1721c863fdc6944d2fd87521d
    search: [linkedin]
  -
    css: meetup
    code: 0x4d
    uid: 3da502d7bf60ce54298aafe7b6dca55f
    search: [meetup]
  -
    css: vk
    code: 0x4e
    uid: 12db1f260b5b2ccd1aa4d8942cc7f6dd
    search: [vkontakte]
  #-
  #  css: 4f
  #  code: 0x4f
  #  uid: 763a39e511a40c6ce27106276d6e1b02
  #  search: []
  -
    css: plancast
    code: 0x50
    uid: 6cc1c059e221d7a0bf109870cc48f1a5
    search: [plancast]
  -
    css: disqus
    code: 0x51
    uid: 9b345d273b96183674779e05d64274af
    search: [disqus]
  -
    css: rss
    code: 0x52
    uid: 2a3192d0f8fe0c7cf959168e68eb16d8
    search: [rss]
  -
    css: skype
    code: 0x53
    uid: 1884ff7f89cc02840606d28f9bcf930a
    search: [skype]
  -
    css: twitter
    code: 0x54
    uid: b1ec8e90c2c85cf0035849980a3789b3
    search: [twitter]
  -
    css: youtube
    code: 0x55
    uid: 57a4f84c40a0c44d47387105f162a427
    search: [youtube]
  -
    css: vimeo
    code: 0x56
    uid: e47352cd4c5e069288b29a2c9ab9d305
    search: [vimeo]
  -
    css: windows
    code: 0x57
    uid: 01dcfef491cd3603565e4a68d1805332
    search: [windows]
  -
    css: xing
    code: 0x58
    uid: d2f0cf090ba9e1a4ecbf8275018a0d61
    search: [xing]
  -
    css: yahoo
    code: 0x59
    uid: aa86b5f7dd6d1087f35cbed951970cd1
    search: [yahoo]
  #-
  #  css: 5a
  #  code: 0x5a
  #  uid: de57dabc07d7b876c39d5937595aadc3
  #  search: []
  -
    css: chrome
    code: 0x5b
    uid: 261a9fed5c3e5883ecc99e354d78a94b
    search: [chrome]
  #-
  #  css: 5c
  #  code: 0x5c
  #  uid: 0c4930a1f379b7c8f68752000e88bbf1
  #  search: []
  -
    css: email
    code: 0x5d
    uid: a58032f4aafd0eec54803075f5b320d4
    search: [email]
  -
    css: macstore
    code: 0x5e
    uid: 94b684c4b484712a2506911b68446ad9
    search: [macstore]
  -
    css: myspace
    code: 0x5f
    uid: 916eba314d66dee45c9859d2fd146d36
    search: [myspace]
  -
    css: podcast
    code: 0x60
    uid: 5287c0dd80c29636f3d45b8b52cd3021
    search: [podcast]
  -
    css: amazon
    code: 0x61
    uid: 2f85c90013c0af641d18b167ec93d165
    search: [amazon]
  -
    css: steam
    code: 0x62
    uid: 785a9b232e86ae750516adc5228a5aa7
    search: [steam]
  -
    css: cloudapp
    code: 0x63
    uid: 6c304f746d790c6749f345ac384cbd7c
    search: [cloudapp]
  -
    css: dropbox
    code: 0x64
    uid: d0ce443b8d7376716584f5f660a6bf72
    search: [dropbox]
  -
    css: ebay
    code: 0x65
    uid: eae6db03eb0c9f2673a126967bf4d4ed
    search: [ebay]
  -
    css: facebook
    code: 0x66
    uid: 6f7586c6f99798c3c1de6123d1f6cfa9
    search: [facebook]
  -
    css: github
    code: 0x67
    uid: 9bba5df43e4e9419975336161e1810c3
    search: [github]
  -
    css: github-circled
    code: 0xE8
    uid: ff16079eb4be12c49bf3014d2322acdd
    search: [github]
  -
    css: googleplay
    code: 0x68
    uid: 909f99f11c6b6551bf757b6e809f98f3
    search: [googleplay]
  -
    css: itunes
    code: 0x69
    uid: d6096cb47cc4448ac68b6a2e2c52a81d
    search: [itunes]
  -
    css: plurk
    code: 0x6a
    uid: bc3411a07338a7ae2dc49b9720f792c5
    search: [plurk]
  -
    css: songkick
    code: 0x6b
    uid: df750854b73c819540447f621729fb3a
    search: [songkick]
  -
    css: lastfm
    code: 0x6c
    uid: f3d8d921ab15972d3a29da321c5c0558
    search: [lastfm]
  -
    css: gmail
    code: 0x6d
    uid: b49fa3e57e92b38143e0fdcc5d9a904b
    search: [gmail]
  -
    css: pinboard
    code: 0x6e
    uid: c91522256a4c3972e9a2765b995b7252
    search: [pinboard]
  -
    css: openid
    code: 0x6f
    uid: 1cf32a32df11230cd182b593752304b4
    search: [openid]
  #-
  #  css: 70
  #  code: 0x70
  #  uid: 3f901a48a45300ad9834b75d23d0fab4
  #  search: []
  -
    css: quora
    code: 0x71
    uid: 6a85bc0b09a4f21d2a3ced2bdffbc770
    search: [quora]
  #-
  #  css: 72
  #  code: 0x72
  #  uid: 0d695a27a88e428474fa5c0641f33f2c
  #  search: []
  -
    css: soundcloud
    code: 0x73
    uid: 1e123339045e48ddd01031936b9fc2d9
    search: [soundcloud]
  -
    css: tumblr
    code: 0x74
    uid: 90d3360c550556afb7e5d3ea58a34e43
    search: [tumblr]
  #-
  #  css: 75
  #  code: 0x75
  #  uid: 7268b65c30b21c3356468578d82f9a3f
  #  search: []
  -
    css: eventasaurus
    code: 0x76
    uid: 60750bcb027f99557abe2fab47f19f2e
    search: [eventasaurus]
  -
    css: wordpress
    code: 0x77
    uid: 0636c283a9822288a767609062bbf4a4
    search: [wordpress]
  #-
  #  css: 78
  #  code: 0x78
  #  uid: 45e4634ae47238dd0bbc16da91d87817
  #  search: []
  -
    css: yelp
    code: 0x79
    uid: 5d8165146a6d5f2784982aa955f963ce
    search: [yelp]
  #-
  #  css: 7a
  #  code: 0x7a
  #  uid: 9825bbc5032268162582f2fbcf5a61b8
  #  search: []
  -
    css: intensedebate
    code: 0x7b
    uid: 67a821c2e9dbc2e439142b4aa04a9c4e
    search: [intensedebate]
  -
    css: eventbrite
    code: 0x7c
    uid: d99bb6de425328eea70522711d17596d
    search: [eventbrite]
  -
    css: scribd
    code: 0x7d
    uid: d549e369e55576b49f999436b9f13f44
    search: [scribd]
  -
    css: posterous
    code: 0x7e
    uid: 0ec44644bdb6b89bbedb8929bb343a61
    search: [posterous]
  -
    css: stripe
    code: 0xa3
    uid: 3e10dfa19399b45e9dbb9134c849334f
    search: [stripe]
  #-
  #  css: ad
  #  code: 0xad
  #  uid: 51ee54a564ad2ec568d58250cbc57685
  #  search: []
  -
    css: opentable
    code: 0xc7
    uid: 7ac996dea1fe6954e68548f0d73cd2b1
    search: [opentable]
  -
    css: cart
    code: 0xc9
    uid: c1f0120c5cb9af80a2f56d7d7fb2f489
    search: [cart, basket]
  -
    css: print
    code: 0xd1
    uid: 6dd44b2efdc8c7bb99cbc75ed13b4c1e
    search: [print]
  -
    css: angellist
    code: 0xd6
    uid: bdaca8aa91638109e25d72f1dcbb58c1
    search: [angellist]
  -
    css: instagram
    code: 0xdc
    uid: 6275b63473065457219b9e12024f95f2
    search: [instagram]
  -
    css: dwolla
    code: 0xe0
    uid: f39ab571fe73e796e24bb8edc1f9d875
    search: [dwolla]
  -
    css: appnet
    code: 0xe1
    uid: 40ff77423c882ef32d11b5aec4ab17cf
    search: [appnet]
  -
    css: statusnet
    code: 0xe2
    uid: 21a454e018faae9de83d19c65e7448d9
    search: [statusnet]
  -
    css: acrobat
    code: 0xe3
    uid: fd1c420f4755e275d578d856d7b20c50
    search: [acrobat]
  -
    css: drupal
    code: 0xe4
    uid: 9794e9b767f192e0d499dfc98d52e802
    search: [drupal]
  -
    css: buffer
    code: 0xe5
    uid: 58b5f27abdf85c2b2b8db2770d61162d
    search: [buffer]
  -
    css: pocket
    code: 0xe7
    uid: a7632b6db17256019e34ec72fb236be0
    search: [pocket]
  -
    css: bitbucket
    code: 0xe9
    uid: 5b1387fb48babf0748ea04107c9adac3
    search: [bitbucket]
  -
    css: lego
    code: 0xEA
    uid: 15a2a7646f0f7c0f129bee0f790d12fc
    search: [lego]
  -
    css: login
    code: 0xEB
    uid: 1dabc07fb86333ee947c283f74ab5fc8
    search: [login]
  -
    css: stackoverflow
    code: 0xEC
    uid: e7d17d4d07756f4ab5eb690eea1275ca
    search: [stack overflow]
  -
    css: hackernews
    code: 0xEd
    uid: 054a8f79ee2dae6c1ba909cc0c6f0cf9
    search: [hacker news]
  -
    css: lkdto
    code: 0xEE
    uid: 2634442580bb3c5c7d87f30bed0227a8
    search: [lkdto]



